### ISSUE TITLE
compile files for V02 requires python3-dev

### ISSUE THREAD

**Issue by jhrehanoaa** [NOAA-OWP/t-route#127]
When trying to compile the files on the Linux workstation I ran into the error.  The fix for this online should be a "sudo apt-get install python3-dev". However, we are not permitted to sudo install. 

python_routing_v02]$ gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -fno-strict-aliasing -Wall -Wstrict-prototypes -fPIC -I numpy_I -I py_I -c mc_reach.c -o mc_reach.o

mc_reach.c:4:20: fatal error: Python.h: No such file or directory
 #include "Python.h"

This comes from the file located at:
../src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/compile_singleSeg_cython.md

**Comment by groutr** [comment]
Compiling a Python C extension requires having the Python header file. I don't use the system python, but instead use a python installed inside a conda environment, which doesn't require sudo permissions to setup.

**Comment by jhrehanoaa** [comment]
I appreciate it. I will make a new environment for it.
