### ISSUE TITLE
`Supernetwork` Function naming update for consistency between v01 and v02

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#132]
Three related small fixes:
Rename ~~`set_networks`~~ to `set_supernetwork_data` in v01 [in v01 compute file here](https://github.com/NOAA-OWP/t-route/blob/930e999770ef8a4e2ac9e36ecdeb06b685e7d42d/src/python_framework_v01/nhd_network_utilities_v01.py#L745).

Rename ~~`set_supernetwork_data`~~ to `set_supernetwork_parameters` in v02 and make return `supernetwork_parameters` [in v02 compute file here](https://github.com/NOAA-OWP/t-route/blob/930e999770ef8a4e2ac9e36ecdeb06b685e7d42d/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L163).

Consider a name such as `routelink_data` for ~~`data`~~ [in v02 compute file here](https://github.com/NOAA-OWP/t-route/blob/930e999770ef8a4e2ac9e36ecdeb06b685e7d42d/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L171).

**Comment by jhrehanoaa** [comment]
#135 should be taken care of now in the draft
