### ISSUE TITLE
convert to command-line inputs

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#14]
Many of the test scripts (e.g. nhd_network_traversal.py, nhd_reach_parallel_test.py) have debug_level, verbose, and supernetwork selection. Make these command-line inputs so that commits do not have to track any testing changes.

**Comment by jameshalgren** [comment]
PR #29 is working on this. There will be a few additional PRs to finish this issue.

**Comment by jameshalgren** [comment]
Need to use the argparse feature `choices` (see fifth program block here: https://docs.python.org/2/howto/argparse.html#combining-positional-and-optional-arguments)

**Comment by jhrehanoaa** [comment]
Should we consider this issue technically closed for now?

**Comment by jhrehanoaa** [comment]
Closed by #42
