### ISSUE TITLE
Transition .json input to .yaml

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#143]
Currently, in the /test/input/json folder, we have `CustomInput.json` (and, if #137 is pulled through, `CustomInput_short.json`) which provide input control for two test cases in the v01 model versions. 

It would be very helpful if comments could be added to these files, so I am suggesting that we convert them to .yaml format and make the necessary changes in the input functions to manage that. 

As a side issue, we could also move the function to make those reads into the v02 `nhd_io.py` file and call the function from both v01 and v02 models. 

@awlostowski-noaa tagging you for continuity in the discussion.

**Comment by jhrehanoaa** [comment]
Finished in V1 not in V2

**Comment by jameshalgren** [comment]
Closed with #149
