### ISSUE TITLE
Add Courant output capability to the MC algorithm

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#150]
The #111 PR has modifications to the MC Algorithm. This issue documents the request to add Courant output capability 

_Originally posted by @awlostowski-noaa in https://github.com/NOAA-OWP/t-route/pull/111#issuecomment-695038042_

**Comment by jameshalgren** [comment]
# Plan
* Add Courant Function to MC...NOLOOP.f90
* port [Colab notebook] (https://colab.research.google.com/drive/19H2obDxGMu_bXyfozoVZFD9s3uy9SuWl#scrollTo=7KHbU2VxqpOq) with Courant-related numerical dispersion experiment
* create (possibly in another PR) notebook demonstrating Courant effect in a real simulation

-- "Choosing a timestep ..."

**Comment by jameshalgren** [comment]
The following kernel may be a beginning: 
``` 
def celerity_kernel(h, bfd, bw, twcc, ncc, s0, n, z):
 
    h_gt_bf = max(h - bfd, 0)
    h_lt_bf = min(bfd, h)
 
    AREA = (bw + h_lt_bf * z ) * h_lt_bf
    WP = (bw + 2 * h_lt_bf * np.sqrt(1 + z*z))
    AREAC = (twcc * h_gt_bf)  # Goes to zero below bankfull
    if h_gt_bf > 0:
        WPC = twcc + (2 * (h_gt_bf))  # Goes to zero below bankfull
    else: 
        WPC = 0
    R   = (AREA + AREAC)/(WP + WPC)
    
    ckC = ((np.sqrt(s0)/n)* \
            ((5/3)*R**(2/3) - ((2/3)*R**(5/3)* \
            (2*np.sqrt(1 + z*z)/(bw+2*h_lt_bf*z))))*AREA \
                + ((np.sqrt(s0)/(ncc))*(5/3)*(h_gt_bf)**(2/3))*AREAC)/(AREA+AREAC)
 
    return ckC
```

**Comment by jameshalgren** [comment]
Also, this is the beginning of a fortran celerity function: 
```
!**---------------------------------------------------**!
!*                                                     *!
!*                CELERITY SUBROUTINE                  *!
!*                                                     *!
!**---------------------------------------------------**!
subroutine celerity_kernel (h, bw, bfd, twcc, s0, n, ncc)

    implicit none

    real(prec), intent(in) :: h, bw, bfd, twcc, s0, n, ncc

    real(prec) :: AREA, WP, R, Ck, Km, X, D
    integer    :: upper_interval, lower_interval
...
```

**Comment by awlostowski-noaa** [comment]
# Plan, revised
- @awlostowski-noaa create new branch: "courant"
- Merge #111 
- rebase courant branch
- create a new PR on this issue
- Add courant subroutine to MC...NOLOOP.f90
- Create a notebook illustrating the use and utility of the courant subroutine for evaluating numerical state of routing simulations. Consider both a simple single reach network and a more complex subset of the NHD network. The latter may end up being a PR of its own.
- Review literature on timestep selection for network routing problems. Specifically [this paper](https://journals.ametsoc.org/jhm/article/12/5/913/5717)

**Comment by jameshalgren** [comment]
@awlostowski-noaa 
This kernel is slightly better -- it incorporates a linear transition into the compound channel so there is not hard break in the `(AREA+AREAC)` and `(WP+WPC)` values.
 
``` python
def celerity_kernel(h, bfd, bw, twcc, ncc, s0, n, z):
    
    h_gt_bf = max(h - bfd, 0)
    h_lt_bf = min(bfd, h)
    twcc_trans_depth = 0.1  # Assign a very small number for unscaled transition to compound channel
    twcc_factor = min((h_gt_bf / twcc_trans_depth), 1.0)
    twcc_scaled = twcc * twcc_factor
 
    AREA = (bw + h_lt_bf * z ) * h_lt_bf
    WP = (bw + 2 * h_lt_bf * np.sqrt(1 + z*z))
    AREAC = (twcc_scaled * h_gt_bf)  # Goes to zero below bankfull
    WPC = twcc_scaled + (2 * (h_gt_bf))  # Goes to zero below bankfull
    R   = (AREA + AREAC)/(WP + WPC)
    
    ckC = ((np.sqrt(s0)/n)* \
            ((5/3)*R**(2/3) - ((2/3)*R**(5/3)* \
            (2*np.sqrt(1 + z*z)/(bw+2*h_lt_bf*z))))*AREA \
                + ((np.sqrt(s0)/(ncc))*(5/3)*(h_gt_bf)**(2/3))*AREAC)/(AREA+AREAC)
 
    return ckC
```

**Comment by jameshalgren** [comment]
@awlostowski-noaa 
Two additional topics to write down so we that can discuss later: 
1) `df.apply`: If we add another axis to the dataframe "depth" in the example, containing all of the constant parameters in df, then we could probably use df.apply with a lambda function built around the celerity kernel to quickly calculate the celerity/courant number. See [SO example here](https://stackoverflow.com/questions/13331698/how-to-apply-a-function-to-two-columns-of-pandas-dataframe). 
1) `optional`: The Fortran 90 specification allows for the use of optional variables. These are basically added at the end of the call string and, if they don't show up, don't throw an error when called. Obviously, there has to be some kind of handling for them. Using an optional output for ck such as shown in the **untested code** below, could be a way to add courant output capability to the MC algorithm while relatively easily maintaining backward compatibility -- we would write another function called singlesegment_courant with the additional returns but it would call the same `mc.muskingcungenwm`, only with additional arguments to receive the additional optional output.

References on the `optional` keyword.
[Old, clear (but slightly less directly applicable)](https://ergodic.ugr.es/cphys/LECCIONES/FORTRAN/f77to90/c8.html)
[A similar post](http://www.netlib.org/ccm/page/api/optional.html)
[A newer, nearly exact SO question, with cryptic but probably important answers](https://stackoverflow.com/questions/3121954/fortran-90-presence-of-optional-arguments)

``` fortran
subroutine muskingcungenwm(dt, qup, quc, qdp, ql, dx, bw, tw, twcc,&
    n, ncc, cs, s0, depthp, qdc, velc, depthc, bfdout, ckout)

    implicit none

    real(prec), intent(in) :: dt
    real(prec), intent(in) :: qup, quc, qdp, ql
    real(prec), intent(in) :: dx, bw, tw, twcc, n, ncc, cs, s0
    real(prec), intent(in) :: depthp
    real(prec), optional, intent(out) :: bfd
    real(prec), optional, intent(out) :: ck
    real(prec) :: z
    real(prec) :: bfd, C1, C2, C3, C4
    
    ...
    if present (ckout) then
        ckout = computedck
    endif

```

**Comment by awlostowski-noaa** [comment]
# Issue Update
1. A new subroutine is added to the MC module to calculate the courant number and kinematic celerity.  Rather than directly editing, MC...NOLOOP.f90, I created a [development copy](https://github.com/awlostowski-noaa/t-route/blob/courant/src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/courant_dev/MCsingleSegStime_f2py_NOLOOP-anw.f90).
2. [A new Jupyter Notebook](https://github.com/awlostowski-noaa/t-route/blob/courant/src/fortran_routing/mc_pylink_v00/MC_singleSeg_singleTS/courant_dev/parity_test.ipynb) shows that the additional Courant subroutine does not change the MC module output (flow, velocity, and depth), relative to the original module. 
## next steps
- Currently working on using "optional" FOTRAN variables to call the Courant subroutine and return output only if additional arguments are passed. This way, we will not need to change MC module calls throughout the repository.

**Comment by awlostowski-noaa** [comment]
# Issue Update
## Numerical strangeness when Courant condition is violated
[A numerical experiment](https://github.com/awlostowski-noaa/t-route/blob/courant/notebooks/courant_test.ipynb) shows how numerical errors manifest in simulated flood waves when the Courant condition is violated. I simulate the propagation of a Gaussian-shaped wave along a 20 km reach composed of 2 km segments with uniform channel geometry. The simulation is run 5 times with timesteps ranging from 30 - 600 seconds. The Courant condition is satisfied (C<1) for timesteps of 30, 60, and 120 seconds. However, the Courant condition is violated (C>1) for timesteps of 300 and 600 seconds. When the Courant condition is violated, simulated waves are delayed with lower than expected peak flows. This appears to be insidious behavior capable of negatively impacting network-scale simulations, while going unnoticed unless the value of the Courant number is analyzed at all time/space steps of the simulation. 

Solid colored lines in the figure below show simulation results at the downstream end of the reach. The dashed black line shows the lateral inflow forcing, which flows into the upstream most segment of the reach. Simulations 0, 1, and 2 are over plotted on one another. The maximum value of the Courant condition at the downstream end of the reach is printed in the legend. Errors arise when C>1.
![image](https://user-images.githubusercontent.com/66840445/95239391-e5859780-07d8-11eb-9961-f489c98bfc46.png)

This experiment justifies our effort to return the courant condition in the standard output of the M-C routing module.
