### ISSUE TITLE
v02 ignores short timestep assumption within reach computations

### ISSUE THREAD

**Issue by awlostowski-noaa** [NOAA-OWP/t-route#156]
## The problem:
`mc_reach.compute_reach_kernel` is written in such a way that it automatically **does not** assume a short timestep. In the code snippet below, we see that a chained assignment defines `quc` as `qdc` at the end of one single segment calculation and just prior to the next:

    for i in range(nreach):
        qlat = input_buf[i, 0] # n x 1
        dt = input_buf[i, 1] # n x 1
        dx = input_buf[i, 2] # n x 1
        bw = input_buf[i, 3]
        tw = input_buf[i, 4]
        twcc =input_buf[i, 5]
        n = input_buf[i, 6]
        ncc = input_buf[i, 7]
        cs = input_buf[i, 8]
        s0 = input_buf[i, 9]
        qdp = input_buf[i, 10]
        velp = input_buf[i, 11]
        depthp = input_buf[i, 12]

        muskingcunge(
                    dt,
                    qup,
                    quc,
                    qdp,
                    qlat,
                    dx,
                    bw,
                    tw,
                    twcc,
                    n,
                    ncc,
                    cs,
                    s0,
                    velp,
                    depthp,
                    out)

        output_buf[i, 0] = quc = out.qdc # this will ignore short TS assumption at seg-to-set scale?
        output_buf[i, 1] = out.velc
        output_buf[i, 2] = out.depthc

        qup = qdp

## Proposed solution
If we want to perfectly re-create the behavior of WRF, *I think* this needs to be revised with a conditional statement like:

        if assume_short_ts:
            quc = qup
        else:
            quc = out.qdc

AND we should revise the how we fill the first column of the output_buf as: `output_buf[i,0] = out.qdc`

If I am correct in my understanding the short timestep assumption, then these minor changes can be made as a part of the ongoing [initial conditions pull request](https://github.com/NOAA-OWP/t-route/pull/131). To make this happen, we would need to pass the `assume_short_ts` variable from `mc_reach.compute_network` to `mc_reach.compute_reach_kernel`.

## Why did I find this issue?
I am having difficulty reproducing WRF hydro results with v02. I observe that v02 simulated flows gradually depart from WRF simulated flows. This flow departure increases for segments along a single reach, such that headwater segments match almost exactly the WRF results, but as we move downstream, v02 simulated flows become gradually greater than WRF simulated flows. 
A headwater segment:
![image](https://user-images.githubusercontent.com/66840445/95577168-a1281080-09ff-11eb-8b97-9fc6f5963714.png)

3 segments downstream on the same reach:
![image](https://user-images.githubusercontent.com/66840445/95577361-011eb700-0a00-11eb-8450-5f0f81e94be5.png)

I am puzzled by these systematic late-time departures from the WRF results that stack up at the bottom of individual reaches and subnetworks. **NOTE** The results above pass `assume_short_ts = True` to `mc_reach.compute_network` and if `assume_short_ts = False` these errors are even worse. 

## I'm usually wrong
I usually need to test and refute a bunch of hypotheses before finding a solution. I don't know that the changes I am proposing will fix my v02 - WRF parity issue, but I figured this issue can gin up a conversation.

**Comment by awlostowski-noaa** [comment]
## Solution
Tried and tested the above changes, here is what I observed.

Parameters of my test:
- 5 minute timesteps
- lateral flow, initial flow and initial depth read directly from WRF output files
- `assume_short_ts=True` in `mc_reach.compute_network` call

Before implementing the above changes, here is the behavior observed at the network tailwater:
![image](https://user-images.githubusercontent.com/66840445/95579723-21507500-0a04-11eb-8ba4-42eef5b3bbdf.png)

After implementing the above changes, v02 simulations seem to match WRF hydro simulations exactly:
![image](https://user-images.githubusercontent.com/66840445/95580259-0c281600-0a05-11eb-8923-ebae3bc24768.png)

Finally, let's see what the behavior looks like when we throw the short timestep assumption out the window (i.e. `assume_short_ts = False` ).
![image](https://user-images.githubusercontent.com/66840445/95580369-38439700-0a05-11eb-92e2-adc0818301a3.png)

**Just because we can match WRF simulation results exactly, doesn't mean they are correct**

**Comment by jameshalgren** [comment]
> `mc_reach.compute_reach_kernel` is written in such a way that it automatically **does not** assume a short timestep.

Correct. I've seen that too. I think it was prototyped early on, but then in the latest round of updates, the capability was dropped when the code was reorganized for more efficient buffer handling. I think your proposed change is probably the right idea -- I'm tagging @grout here and we should make sure we include him on the review of #131 before that goes in.

**Comment by jameshalgren** [comment]
> ## I'm usually wrong
I'm glad that you are often right, too.
> I usually need to test and refute a bunch of hypotheses before finding a solution. I don't know that the changes I am proposing will fix my v02 - WRF parity issue, but I figured this issue can gin up a conversation.
I have been making sure that all my tests strictly reproduce the output of the csv files generated by executing `compute_nhd_routing_SingleSeg.py --test --sts`. To be specific, I have been checking 4186169.csv -- I've attached the __STS__ and __NOSTS__ versions of several including that one here.

We can work towards confirming that v02 simulations reproduce the same output.
[courant_STS_4185243.csv.txt](https://github.com/NOAA-OWP/t-route/files/5357992/courant_STS_4185243.csv.txt)
[courant_STS_4186169.csv.txt](https://github.com/NOAA-OWP/t-route/files/5357993/courant_STS_4186169.csv.txt)
[courant_NOSTS_2743020.csv.txt](https://github.com/NOAA-OWP/t-route/files/5357994/courant_NOSTS_2743020.csv.txt)
[courant_NOSTS_4185243.csv.txt](https://github.com/NOAA-OWP/t-route/files/5357995/courant_NOSTS_4185243.csv.txt)
[courant_NOSTS_4186169.csv.txt](https://github.com/NOAA-OWP/t-route/files/5357996/courant_NOSTS_4186169.csv.txt)
[courant_STS_2743020.csv.txt](https://github.com/NOAA-OWP/t-route/files/5357997/courant_STS_2743020.csv.txt)
