### ISSUE TITLE
Read initial states from WRF-Hydro decks

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#20]
Moving towards operational implementation as an element of the National Water Model to execute in tandem with the WRF-Hydro computation of lateral contributions to the channels, we need to be able to read the states of the channel depths and flows to initialize forecast simulations.

**Comment by jameshalgren** [comment]
This test file might be used for a first cut... https://github.com/NCAR/wrf_hydro_nwm_public/blob/master/tests/local/examples/ex3_run_croton_docker.sh

**Comment by jhrehanoaa** [comment]
closed by PR #90
