### ISSUE TITLE
Optimize fill_mask using direct boolean mask

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#205]
Here we are reading data out of a numpy array into a list and then back into a numpy array. I wonder if it would be faster to construct a mask and then mask data_idx and flowveldepth using the same mask.

```python
fill_mask = np.ones_like(data_idx, dtype=bool)
fill_mask[list(fill_index_mask)] = 0
return np.asarray(data_idx[fill_mask], dtype=np.intp), np.asarray(flowveldepth_ma[fill_mask], dtype='float32')
```
Based on what is going on with fill_index_mask, a boolean mask should work here.

_Originally posted by @groutr in https://github.com/NOAA-OWP/t-route/pull/188#r555897443_

**Comment by awlostowski-noaa** [comment]
Am waiting for #188 to merge before working on this and #204

**Comment by groutr** [comment]
Another pass over the code showed me that we can construct `fill_mask` directly without creating a `fill_index_mask` set.
In `compute_network` make `fill_index_mask` an array instead of a set.
```python
cdef bint[:] fill_index_mask = np.ones_like(data_idx, dtype=bool)
cdef Py_ssize_t fill_index
cdef long upstream_tw_id
cdef dict tmp
for upstream_tw_id in upstream_results:
    tmp = upstream_results[upstream_tw_id]
    fill_index = tmp["position_index"]
    fill_index_mask[fill_index] = False
    flowveldepth[fill_index] = tmp["results"]
```

**Comment by awlostowski-noaa** [comment]
Then simply, 
```python
if fill_index_mask.count(False) > 1:
     return np.asarray(data_idx[fill_index_mask], dtype=np.intp), np.asarray(flowveldepth_ma[fill_index_mask], dtype='float32')
else
     return [np.asarray(data_idx, dtype=np.intp), np.asarray(flowveldepth, dtype='float32')]

```
??

**Comment by awlostowski-noaa** [comment]
Because this action happens with gil, is it necessary to cdef these variables?

```python
cdef Py_ssize_t fill_index
cdef long upstream_tw_id
cdef dict tmp
```

**Comment by groutr** [comment]
@awlostowski-noaa There is no need to count the mask. Just apply it. If no values are masked out, the result is equivalent to unmasked array.

We need to type the variables used in the loop so Cython can optimize the loop efficiently.
