### ISSUE TITLE
[15pt] α solution: (i) Check bottlenecks & (ii) Different hydro approaches (using Jup. Notebook vers of α)

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/t-route#232]

**Comment by GregCocks-NOAA** [comment]
• break out α solution into Jupyter notebook so as to be better able to research possible time bottlenecks at CONUS level and possible hydrologic adjustments (e.g., Strahler stream order?)

**Comment by GregCocks-NOAA** [comment]
python profilers and similar approaches?
---
https://www.infoworld.com/article/3600993/5-great-libraries-for-profiling-python-code.html
---
https://jakevdp.github.io/PythonDataScienceHandbook/01.07-timing-and-profiling.html
