### ISSUE TITLE
 Evaluate impact of additional output (Cn Ck X) on CONUS execution...

### ISSUE THREAD

**Issue by jhrehanoaa** [NOAA-OWP/t-route#238]
- [x] Evaluate impact of additional output (Cn Ck X) on CONUS execution...

_Originally posted by @jameshalgren in https://github.com/NOAA-OWP/t-route/issues/223#issuecomment-778346965_

**Comment by jameshalgren** [comment]
Completed as part of the evaluation of the Florence test case PR #223
