### ISSUE TITLE
Add segment filtering to CSV output

### ISSUE THREAD

**Issue by jhrehanoaa** [NOAA-OWP/t-route#239]
- [x] TODO: Make new issue regarding CSV file filtering to apply currently-unused options in .yaml control file.
See additional comments here: https://github.com/jhrehanoaa/t-route/pull/4/files#r575502732
> - [x] New issue/New Pull Request "Add segment filtering to CSV output"
    - [ ] Change these segment IDs to something relevant for the domain to be tested (if we use "CustomInput.yaml, they should already work...)
    - [ ] Test placing a filter on the csv output to limit data to the specified IDs
    - [ ] Make sure that if `csv_output_segments` is missing, the output is the full set.
    - [ ] If `csv_output_segments` is `[]` output an empty csv (with the header) for testing.
    - [ ] if `csv_output` is missing from the .yaml, make sure it doesn't crash

_Originally posted by @jameshalgren in https://github.com/NOAA-OWP/t-route/issues/223#issuecomment-778347480_

**Comment by jameshalgren** [comment]
> * - [ ] if `csv_output` is missing from the .yaml, make sure it doesn't crash

Moving this item to a new issue...
