### ISSUE TITLE
Add a reservoir restart and reservoir file to Florence test

### ISSUE THREAD

**Issue by jhrehanoaa** [NOAA-OWP/t-route#240]
ping @jhrehanoaa 
Let's try to finish without
`test/input/florence_933020089/RESTART/HYDRO_RST.2018-09-XX_00_00_DOMAIN1`
and
`test/input/florence_933020089/DOMAIN/LAKEPARM.nc`

Then this should be clean. 

- [x] Make a new issue to add a reservoir restart and reservoir file to this test (will require permission for LAKEPARM)

_Originally posted by @jameshalgren in https://github.com/NOAA-OWP/t-route/pull/223#issuecomment-777075997_

**Comment by JurgenZach-NOAA** [comment]
Addressed in PR223 (Florence test case obsolete by now)
