### ISSUE TITLE
Remove redundant arguments

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#251]
We need only pass `run_parameters` -- the `return_courant`, `nts`, and `dt` are all extractable from there as subelements. 

run_parameters.get["return_courant", False"]
run_parameters["nts"],
run_parameters["dt"],

https://github.com/NOAA-OWP/t-route/blob/afd4ee3502b3c214dc6c4b81b62892eefc3e471a/src/python_routing_v02/build_tests.py#L160

**Comment by jhrehanoaa** [comment]
closed by #269
