### ISSUE TITLE
Incorporate reservoir compile process into existing setup.py

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#254]
The new reservoir capability #224 introduces additional compile and install needs. (See https://github.com/NOAA-OWP/t-route/blob/master/src/fortran_routing/Reservoir_Binding/kernels/readme.md)

These need to be incorporated into the compiler script: 
https://github.com/NOAA-OWP/t-route/blob/master/src/python_routing_v02/compiler.sh

(the compiler script probably belongs somewhere else and could use other updates as well, but we'll take this first step...)

**Comment by jameshalgren** [comment]
ping @hellkite500 

cd to src/fortran_routing/Reservoir_Binding/kernels/fortran/...
run `make` (will need to set the fortran include and lib directories.)
drop back down to Reservoir_Binding
run `python setup.py install`

Those instructions are in the readme.py and should work out of the box. If you are on your own os, install libnetcdff (two 'f's) to get the fortran netcdf bindings and things should work.

**Comment by hellkite500** [comment]
I think the reference PR above (number 24) isn't quite right.  Regardless, I think this addressed in #263

**Comment by jameshalgren** [comment]
> I think the reference PR above (number 24) isn't quite right. Regardless, I think this addressed in #263

#224. And yes.
