### ISSUE TITLE
Remove routelink from index history

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/t-route#26]
Short description explaining the high-level reason for the new issue.

## Current behavior

A clone will still pull the indexed routelink file.

## Expected behavior

Routelink is downloaded by application, and is not included in version control.

## Steps to replicate behavior (include URLs)

clone repo, wait a while.

Proposed fix:

Use BFG to remove the file from git history, will require a force push and full re-sync of all forks/clones (will re-write history.)

**Comment by jameshalgren** [comment]
We'll find a window when the re-sync will be less disruptive.

**Comment by jameshalgren** [comment]
We could probably do that this week. If we are going to force a re-sync, perhaps we can also black the files during the process.

**Comment by jameshalgren** [comment]
Closed. See #160
