### ISSUE TITLE
cython build on FIPS system fails

### ISSUE THREAD

**Issue by jhrehanoaa** [NOAA-OWP/t-route#278]
After the recent pushes last week I can no longer run ```./compiler.sh``` on any branches without running into errors. We corrected this on Cheyenne by running ```module purge && module load  ncarenv/1.3  gnu/9.1.0  ncarcompilers/0.5.0  mpt/2.22  netcdf/4.7.4```. If there are any hotfixes for this it would be appreciated. The purge and load does not work on the Linux workstation. 

rm -f *.o *.mod
gfortran -g -c -O2 -fPIC varPrecision.f90
gfortran -g -c -O2 -fPIC -o mc_single_seg.o MCsingleSegStime_f2py_NOLOOP.f90
gfortran -g -c -O2 -fPIC -o pymc_single_seg.o pyMCsingleSegStime_NoLoop.f90
gfortran -g -c -O2 -fPIC -o module_levelpool.o ../Reservoir_singleTS/module_levelpool.f90
gfortran -g -c -O2 -fPIC -o pymodule_levelpool.o ../Reservoir_singleTS/pymodule_levelpool.f90
cp *.o ../../../../src/python_routing_v02/fast_reach
rm -f *.o
rm -f *.mod
rm -f *.a
rm -f reservoir_tests
rm -f test_main
gfortran -g -w -c -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4 -I -static-libgfortran -static-libgcc -nodefaultlibs -lgfortran -lgcc -fPIC -L -lnetcdff -lnetcdf -c -o module_reservoir.o module_reservoir.F
Warning: Nonexistent include directory "-static-libgfortran"
gfortran -g -w -c -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4 -I -static-libgfortran -static-libgcc -nodefaultlibs -lgfortran -lgcc -fPIC -L -lnetcdff -lnetcdf -c -o module_levelpool_properties.o ./Level_Pool/module_levelpool_properties.F
Warning: Nonexistent include directory "-static-libgfortran"
gfortran -g -w -c -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4 -I -static-libgfortran -static-libgcc -nodefaultlibs -lgfortran -lgcc -fPIC -L -lnetcdff -lnetcdf -c -o module_levelpool_state.o ./Level_Pool/module_levelpool_state.F
Warning: Nonexistent include directory "-static-libgfortran"
gfortran -g -w -c -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4 -I -static-libgfortran -static-libgcc -nodefaultlibs -lgfortran -lgcc -fPIC -L -lnetcdff -lnetcdf -c -o module_levelpool.o ./Level_Pool/module_levelpool.F
Warning: Nonexistent include directory "-static-libgfortran"
gfortran -g -w -c -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4 -I -static-libgfortran -static-libgcc -nodefaultlibs -lgfortran -lgcc -fPIC -L -lnetcdff -lnetcdf -c -o bind_lp.o bind_lp.f90
Warning: Nonexistent include directory "-static-libgfortran"
ar rc binding_lp.a module_reservoir.o module_levelpool_properties.o module_levelpool_state.o module_levelpool.o bind_lp.o
cp binding_lp.a ../../../python_framework_v02/libs;
Compiling troute/network/reach.pyx because it changed.
Compiling troute/network/reservoirs/levelpool/levelpool.pyx because it changed.
[1/2] Cythonizing troute/network/reach.pyx

Error compiling Cython file:
------------------------------------------------------------
...

cdef extern from *:
    cdef object __pyx_test_dep(object)

@cname('__pyx_TestClass')
cdef class TestClass(object):
    ^
------------------------------------------------------------

TestClass:8:5: Compiler crash in AnalyseDeclarationsTransform

ModuleNode.body = StatListNode(TestClass:4:0)
StatListNode.stats[1] = CnameDecoratorNode(TestClass:8:5,
    cname = '__pyx_TestClass')

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1636, in visit_CClassDefNode
    self._inject_pickle_methods(node)
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1704, in _inject_pickle_methods
    checksum = '0x%s' % hashlib.md5(' '.join(all_members_names).encode('utf-8')).hexdigest()[:7]
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips

Error compiling Cython file:
------------------------------------------------------------
...
  """
    Encapsulation of basic reach properties and functionality
  """
  cdef readonly int id;
  #Keep a python list of ids only for pre/post processing and diagnostics
  cdef readonly long[::1] to_ids
                    ^
------------------------------------------------------------

troute/network/reach.pyx:11:21: Compiler crash in AnalyseDeclarationsTransform

File 'ModuleNode.py', line 124, in analyse_declarations: ModuleNode(reach.pyx:1:0,
    full_module_name = 'troute.network.reach')
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(reach.pyx:1:0)
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(reach.pyx:5:5)
File 'Nodes.py', line 4805, in analyse_declarations: CClassDefNode(reach.pyx:5:5,
    as_name = 'Reach',
    class_name = 'Reach',
    doc = '\n    Encapsulation of basic reach properties and functionality\n  ',
    module_name = '',
    visibility = 'private')
File 'Nodes.py', line 431, in analyse_declarations: StatListNode(reach.pyx:6:2)
File 'Nodes.py', line 1327, in analyse_declarations: CVarDefNode(reach.pyx:11:7,
    modifiers = [...]/0,
    visibility = 'readonly')
File 'Nodes.py', line 1086, in analyse: MemoryViewSliceTypeNode(reach.pyx:11:21,
    name = 'memoryview')

Compiler crash traceback from this point on:
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Compiler/Nodes.py", line 1082, in analyse
    axes_specs = MemoryView.get_axes_specs(env, self.axes)
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Compiler/MemoryView.py", line 535, in get_axes_specs
    cythonscope.load_cythonscope()
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Compiler/CythonScope.py", line 113, in load_cythonscope
    self, cython_scope=self)
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Compiler/UtilityCode.py", line 208, in declare_in_scope
    tree = self.get_tree(entries_only=True, cython_scope=cython_scope)
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Compiler/UtilityCode.py", line 186, in get_tree
    assert not err, err
AssertionError: 
Error compiling Cython file:
------------------------------------------------------------
...

cdef extern from *:
    cdef object __pyx_test_dep(object)

@cname('__pyx_TestClass')
cdef class TestClass(object):
    ^
------------------------------------------------------------

TestClass:8:5: Compiler crash in AnalyseDeclarationsTransform

ModuleNode.body = StatListNode(TestClass:4:0)
StatListNode.stats[1] = CnameDecoratorNode(TestClass:8:5,
    cname = '__pyx_TestClass')

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1636, in visit_CClassDefNode
    self._inject_pickle_methods(node)
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 1704, in _inject_pickle_methods
    checksum = '0x%s' % hashlib.md5(' '.join(all_members_names).encode('utf-8')).hexdigest()[:7]
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    ext_modules = cythonize(ext_modules, compiler_directives={"language_level": 3})
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/home/jacob.hreha/jupyter/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: troute/network/reach.pyx

**Comment by hellkite500** [comment]
This is not t-route failure, it is the build environment:

```
checksum = '0x%s' % hashlib.md5(' '.join(all_members_names).encode('utf-8')).hexdigest()[:7]
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for fips
```
The error comes from cython trying to compute hashes using md5, and the system rejects the use of md5 becuase it assumes (incorrectly in this case) that it is being used for some cryptographic reason which is considered insecure.

This is a known cython issue on fips enabled systems cython/cython#2790.

You can try upgrading cython on the system you are using to build.

**Comment by jhrehanoaa** [comment]
I upgraded to the newest version of Cython, but still no luck.

**Comment by hellkite500** [comment]
@jhrehanoaa what is the cython version you are using?

**Comment by jhrehanoaa** [comment]
When I upgraded it downloaded Cython-0.29.22

**Comment by hellkite500** [comment]
Looking more closely at the cython issue, the fix to use fips approved `sha-1` is v3, which isn't the official release yet.  What python version are you running?  I'm not sure if it makes a large difference on the fips support, but if you have upgraded python versions lately it might have started enforcing them more, so maybe a minor python downgrade will get by until cython releases 3

**Comment by jhrehanoaa** [comment]
Currently, I am running off of Python 3.6.8, but I can try downgrading to see if it helps solve the issue.

**Comment by hellkite500** [comment]
@jhrehanoaa I don't think that is going to help as I start to understand more about the issue.  May have to grab the dev version of cython and use it since the FIPS mode on your system is likely causing the problem.  It didn't use to be activated or configured as strictly, and that config on your machine changed which led to this issue.

**Comment by jhrehanoaa** [comment]
Yeah, it is strange it just started up. I can try switching to the dev cython and rerunning it.

**Comment by JurgenZach-NOAA** [comment]
v3 fixed this

**Comment by hellkite500** [comment]
> v3 fixed this

V3 of what, exactly? Has a build been achieved on a fips system?

**Comment by JurgenZach-NOAA** [comment]
V3 of Cython, as referenced in the discussion, which has been released by now.

**Comment by JurgenZach-NOAA** [comment]
In the process of cleaning up stale issues that can no longer be verified because it concerns releases that are (in this case) over three years old.
