### ISSUE TITLE
Missing image referenced in readme.md

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/t-route#3]
Short description explaining the high-level reason for the new issue.

## Current behavior
readme.md references an image that doesn't exist.

## Expected behavior
Either image should be added to this repository and linked approriately, or readme text should not mention it.

**Comment by jameshalgren** [comment]
There was an image but it was first made with a proprietary tool. We need to remake the image with FOSS libraries and repost.

**Comment by jameshalgren** [comment]
@jhrehanoaa Will you look at rebuilding the bluecyan gif with some sort of python library?
