### ISSUE TITLE
Incorporate automatic linting or other style checking.

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#31]
This is a general TODO item across the entire project.

**Comment by jameshalgren** [comment]
There are other automation elements we need to add... possibly worth additional issues (e.g., travis-style CI, Docker builds, email scrubbing, etc.)

**Comment by groutr** [comment]
@jameshalgren you might look at a source formatter like black too.

**Comment by jameshalgren** [comment]
Adding 'Black' to the contributing instructions. Will be closing this issue soon with PR -- creating new issue for blacking the .ipynb python notebooks.

**Comment by jameshalgren** [comment]
@aaraney 
Austin, here's our thread on the same topic. 

@groutr generated a [notebook formatter script](https://github.com/NOAA-OWP/t-route/blob/1cd573a28ec0e36723358696650ede88d556c1bc/notebooks/formatnb.py) based on black that we're using. The idea (soon) is to incorporate it into a pre-commit hook or something along those lines.

**Comment by jameshalgren** [comment]
- [ ] incorporate https://pre-commit.com/

**Comment by jameshalgren** [comment]
To black all .py source files throughout the repository (to reduce spurious merge artifacts), from repository root, execute: 
```
find src\. -name "*.py" -exec black {} \;
```
