### ISSUE TITLE
Move or Remove "writetoFile" function

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#318]
The `writetoFile` function is floating around in the main script and, if it belongs anywhere, should be in the nhd_io module somewhere. 
https://github.com/NOAA-OWP/t-route/blob/5e0626a918b60a3c4f73b10cc2c0c09935f2eb6e/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L303-L305

It needs to be moved there or removed entirely.

**Comment by jhrehanoaa** [comment]
Need to fix for looping capability.

**Comment by JurgenZach-NOAA** [comment]
Deleted routine: https://github.com/NOAA-OWP/t-route/pull/807
