### ISSUE TITLE
Extend reservoir simulation to all parallel modes

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#321]
The comment [associated with these lines](https://github.com/NOAA-OWP/t-route/blob/fa93df61f8003906dbde03f152d5ae11c8f16064/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L460-L467) and repeated above [these line](https://github.com/NOAA-OWP/t-route/blob/fa93df61f8003906dbde03f152d5ae11c8f16064/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L608-L611) needs to be addressed. The Jit and Jit-clustered parallelization methods presently do not receive valid inputs to support reservoir simulation. 

The [code here](https://github.com/NOAA-OWP/t-route/blob/fa93df61f8003906dbde03f152d5ae11c8f16064/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L832-L844) represents the general idea of the change needed.

https://github.com/NOAA-OWP/t-route/blob/fa93df61f8003906dbde03f152d5ae11c8f16064/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L460-L467

**Comment by jameshalgren** [comment]
I think we'll need to edit the subnetwork creation function to account for breaking networks at water bodies

This `path_func` partial function does the breaking:
https://github.com/NOAA-OWP/t-route/blob/e24d0326c7f4fb7d9d91f3770afe3d19f262577b/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L357 
There was an initial change in the mc_reach.pyx code, but this chunk from the by-network portion of the code will have to be repeated in the by-subnetwork-jit and ...jit-clustered portions of the code.

https://github.com/NOAA-OWP/t-route/blob/e24d0326c7f4fb7d9d91f3770afe3d19f262577b/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L683-L717
and this chunk
https://github.com/NOAA-OWP/t-route/blob/e24d0326c7f4fb7d9d91f3770afe3d19f262577b/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L734-L742

Will need to replace the chunks mentioned in the issue description.

**Comment by awlostowski-noaa** [comment]
![image](https://user-images.githubusercontent.com/66840445/121042509-c1bc8c00-c781-11eb-9318-e73b074a80b8.png)

**Comment by awlostowski-noaa** [comment]
This is the by-subnetwork-jit parallel output from Croton
![image](https://user-images.githubusercontent.com/66840445/121042727-f6304800-c781-11eb-90e0-36033a6ad5cf.png)

**Comment by jameshalgren** [comment]
Recording here that when tested with a `subnetwork_target_size` larger than the network size (effectively forcing "by-network" parallelization") the solution is identical to the `by-network` parallel solution. This indicates that any difference is the result of the subnetwork in-out passing in some way (and, happily, confirms that the general algorithm is at least stable with networks or subnetworks containing the same set of segments.)

**Comment by awlostowski-noaa** [comment]
#327 and #328 - these now enable reservoir simulations from any parallel method

**Comment by jameshalgren** [comment]
All these capabilities finally incorporated with #347
