### ISSUE TITLE
Out of bounds error when returning courant.

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/t-route#323]
https://github.com/NOAA-OWP/t-route/blob/d1a810aa529c4e5f91d96b17a5b998757aa562cd/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L420

This call to `fill_buffer_column` causes an out of bounds exception related to the `dcol`, or `ts_offset + (i-qvd_ts_w)` in the offending call.

**Comment by jhrehanoaa** [comment]
@hellkite500 please see comments on #380

**Comment by jameshalgren** [comment]
closed with #380; See #362 for follow-up.
