### ISSUE TITLE
Data Assimilation missing observations

### ISSUE THREAD

**Issue by awlostowski-noaa** [NOAA-OWP/t-route#331]
How do we handle situations in which, for whatever reason, discharge observations are missing at a gage? Do we just interpolate through missing data? If so - what method should be used? Do we just not substitute observations at timesteps that are missing? If so, do we apply the DA-decay method?

**Comment by jameshalgren** [comment]
As a study on some of the options, please see this notebook: 
https://colab.research.google.com/drive/1U-jABcxtm0zob4bq6mk1EavN-okoaeOZ#scrollTo=lidNXhN9-B-2&uniqifier=1

**Comment by jameshalgren** [comment]
#341 is intended to address this issue...

**Comment by jhrehanoaa** [comment]
closed by #385
