### ISSUE TITLE
Verify DAG property on graphs

### ISSUE THREAD

**Issue by groutr** [NOAA-OWP/t-route#34]
We assume that the network we are working with is a directed acyclic graph. There should be some sort of way to sanity check a new dataset to make sure it meets this assumption.

One way to verify a directed graph is acyclic is to topologically sort it. A graph has a topological sorting if and only if it is a directed acyclic graph.
https://en.wikipedia.org/wiki/Directed_acyclic_graph#Definitions

**Comment by jameshalgren** [comment]
@groutr -- is this still relevant?

**Comment by groutr** [comment]
@jameshalgren yes, the topic is still relevant.
```python
def is_dag(N):
    try:
        for n in kahn_toposort(N):
            pass
        return True
    except:
        return False
```
This only needs to be done one per dataset, but it would be good to expose a function to do that checking.

**Comment by jameshalgren** [comment]
Moving to Phase 4 Technical Debt.
