### ISSUE TITLE
How do we initialize diffusive wave simulations?

### ISSUE THREAD

**Issue by awlostowski-noaa** [NOAA-OWP/t-route#348]
Diffusive wave simulations need to be initialized with flow, celerity, and diffusivity values at every model node. Warm-starting from MC-simulated flows is problematic, because celerity and diffusivity are unknown and a spin-up period is required. What to do?

**Comment by kumdonoaa** [comment]
As discussed, 1) we can take initial values from restart file of not MC but diffusive model.
                   or 2) we can install celerity and diffusivity computation for initial values from MC.  These works may happen after making prototype for CONUS?

**Comment by awlostowski-noaa** [comment]
@kumdonoaa please elaborate on point 2. I am interested to understand how/if we can compute initial celerity and diffusivity estimates from initial MC flow and depth. 

- Celerity is a function of flow, depth and some channel geometry data. What would happen if we calculated initial celerity from MC-simulated initial flow and depth data? Would it put us more in the ball park than just assuming that celerity = 1 initially? 
- Likewise for diffusivity

**Comment by awlostowski-noaa** [comment]
Another option is to run a spin-up simulation, where the spin-up simulation would run from t0-x -> t0, where x is the number of timesteps required to get the model to converge of stable and accurate diffusivity and celerity parameters. Then, at t0, we would have warm states from the diffusive wave model itself.
