### ISSUE TITLE
Courant = true breaks Florence_Benchmark.yaml test case

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#362]
`return_courant: true` breaks execution for the Florence_Benchmark.yaml test case -- this is because the `compute_network_structured` compute kernel does not produce any valid values for courant output and later logic then fails on the empty output. The failure can be tested with this command line: 
```python -m nwm_routing -V2  -f ../../test/input/yaml/Florence_Benchmark.yaml```
Setting `return_courant: false` for the failed test case works. 

Other work (#380) has fixed the courant return for the `compute_network` kernel (indicated in the yaml with `compute_kernel: V02-caching`) but porting the fix to the other kernels requires handling of the reservoirs, which has not yet been prototyped. A simple possibility would be to populate a Nan or Zero array for all Courant returns from reservoirs. That would have implications for later evaluation but may be sufficient to proceed. 

_Originally posted by @jhrehanoaa in https://github.com/NOAA-OWP/t-route/issues/347#issuecomment-880906590_

**Comment by jameshalgren** [comment]
@awlostowski-noaa 
We may need to fix this soon.

**Comment by jameshalgren** [comment]
at line 593 in  __main__py
`pd.concat([pd.DataFrame(r[2], index=r[0], columns=pd.MultiIndex.from_product([range(8641), ["cn", "ck", "X"]]).to_flat_index()) for r in results], copy=False,)`
`pd.concat([pd.DataFrame(r[1], index=r[0], columns=pd.MultiIndex.from_product([range(8640), ["q", "v", "d"]]).to_flat_index()) for r in results], copy=False,)`

**Comment by jameshalgren** [comment]
The issue was that we had added (then subtracted) a timestep to the main array but not to the courant array.

**Comment by jameshalgren** [comment]
#362 fixes this for the V02_caching mode. This does not yet fix the broken test python -m nwm_routing -V2 -f ../../test/input/yaml/Florence_Benchmark.yaml because the yaml file refers to the V02-structured compute method, which does not yet handle the courant output properly.

**Comment by JurgenZach-NOAA** [comment]
Obsolete test case, but issue addressed in PR380
