### ISSUE TITLE
Array index declared as REAL instead of INT

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#363]
When compiling diffusive.f90 `gfortran -g -c -O2 -fPIC -o diffusive.o diffusive.f90` the compiler warns that the index `j` is incorrectly declared as a REAL (when, presumably, it should be an INT...)
``` fortran
diffusive.f90:725.32:

                if((x(j)-xt)*(x(j+1)-xt).le.0)then
                                1
Warning: Legacy Extension: REAL array index at (1)
```

**Comment by JurgenZach-NOAA** [comment]
No warnings of real indices observed during compile test.
