### ISSUE TITLE
Critical: Dt is hard coded at 300 seconds in mc_reach

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#365]
Recent development uncovered an insidious dependence on hard coded dt in the compute_network* processes... __this MUST BE FIXED__. Experiments to explore effects on Courant violation may have had this bug in place and results would be invalid. Many of the other purported benefits of our new framework will depend on consistency in use of that dt value.

The correction needs to be fairly deep -- the dt is passed inside of a parameter array early in the `compute_nhd_routing_v02` function and that will need to be untangled as part of this. 

- [ ] remove magic numbers from mc_reach.pyx
- [ ] untangle dt embedding in table (and check performance impact)

**Comment by jameshalgren** [comment]
Magic numbers in at least the following lines: 
https://github.com/NOAA-OWP/t-route/blob/70e32677509b3e767e1eeeb48be9bb1a76b15a41/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L338
https://github.com/NOAA-OWP/t-route/blob/70e32677509b3e767e1eeeb48be9bb1a76b15a41/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L920
https://github.com/NOAA-OWP/t-route/blob/70e32677509b3e767e1eeeb48be9bb1a76b15a41/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L1227
https://github.com/NOAA-OWP/t-route/blob/70e32677509b3e767e1eeeb48be9bb1a76b15a41/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L1233
https://github.com/NOAA-OWP/t-route/blob/70e32677509b3e767e1eeeb48be9bb1a76b15a41/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L1239

**Comment by jameshalgren** [comment]
@jdmattern-noaa

**Comment by jdmattern-noaa** [comment]
@jameshalgren I assume this should come from the current dt in the yaml file?
https://github.com/NOAA-OWP/t-route/blob/master/test/input/yaml/Croton_NY_levelpool.yaml#L14
