### ISSUE TITLE
Indentation is non-standard in mc_reach.pyx

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#374]
Throughout the file, but affecting this line (which may need a more specific fix), the indentation is non-standard through the MC_Reach.pyx file.  

https://github.com/NOAA-OWP/t-route/blob/341fed06fae03e39a9def8d9165ac47565264492/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L430

**Comment by jhrehanoaa** [comment]
closed with #373
