### ISSUE TITLE
Reduce duplication of DA code in nearly identical code in the three compute kernels

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#387]
The #385 PR implements three sections of nearly identical code in the three compute kernels: 
[lines 229-252](https://github.com/NOAA-OWP/t-route/blob/e8bcd4ba9edb297c647584a157ca794ff8296c58/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L229-L252) and [lines 445-469](https://github.com/NOAA-OWP/t-route/blob/e8bcd4ba9edb297c647584a157ca794ff8296c58/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L445-L469)
[lines 831-855](https://github.com/NOAA-OWP/t-route/blob/e8bcd4ba9edb297c647584a157ca794ff8296c58/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L831-L855) and [lines 1015-1040](https://github.com/NOAA-OWP/t-route/blob/e8bcd4ba9edb297c647584a157ca794ff8296c58/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L1015-L1040)
[lines 1235-1262](https://github.com/NOAA-OWP/t-route/blob/e8bcd4ba9edb297c647584a157ca794ff8296c58/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L1235-L1262) and [lines 1377-1430](https://github.com/NOAA-OWP/t-route/blob/e8bcd4ba9edb297c647584a157ca794ff8296c58/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L1377-L1430) in mc_reach.pyx. 

I'm thinking that we can remove some of the code duplication and hopefully streamline things (both generally desirable goals) for all the inputs if we create a function to handle those calculations. 

The challenge would be that there are slight differences in the handling of timesteps and in the declaration of the flowveldepth arrays. Can anyone think of a way to make a cython function to treat a cdef float[:,::1] and a cdef np.ndarray[float, ndim=3] as synonymous? We have those two constructions in our different compute functions representing the same variables (flowveldepth) and I would like to prepare a single function to initialize them both. In other words, I would like to create a function into which I can pass either the memoryview with 2 dimensions or the nd array with 3 dimensions and, given the congruency of their data storage, populate them equivalently.

One option would be to modify the caching-based version of our function to use the 3-dimensional declaration (so they would all be synchronous.) But that loses the advantages of the typed memoryview, which are more general and more efficiently used with cython. See the following: 

> "Typed memoryviews allow efficient access to memory buffers, such as those underlying NumPy arrays, without incurring any Python overhead. Memoryviews are similar to the current NumPy array buffer support (np.ndarray[np.float64_t, ndim=2]), but they have more features and cleaner syntax."
https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html

With that in mind, I'd prefer to leave the memoryview in place and find a way to convert the array declaration, at least for purposes of handling inside this function.

_Originally posted by @jameshalgren in https://github.com/NOAA-OWP/t-route/issues/385#issuecomment-902110983_

**Comment by jhrehanoaa** [comment]
closed with #385
