### ISSUE TITLE
Confirm no security issue w/download

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#39]
Related to #26 and related to #27 
The automatic download combined with custom file input capabilities, there is some possibility that strange inputs could cause trouble. 

https://github.com/NOAA-OWP/t-route/blob/69f397c72c5d38a6565fbf6c691ec309d81dbd9e/src/python_framework/network_dl.py#L5

**Comment by jameshalgren** [comment]
ping @jhrehanoaa

**Comment by hellkite500** [comment]
If data is downloaded but not trusted, then it needs to be validated  before being processed.
