### ISSUE TITLE
Consolidate argparse into a single script

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#43]
The recently submitted argparse changes could be consolidated into a single argument handling script.

**Comment by jameshalgren** [comment]
Some tips on custom 'usage' instructions are in this S.O. post: 
https://stackoverflow.com/questions/15935092/creating-mutually-inclusive-positional-arguments-with-argparse

**Comment by jhrehanoaa** [comment]
I moved most of the code over to a single script. The nhd_reach_parallel file is getting hung up on the reservoir inputs though.

**Comment by jhrehanoaa** [comment]
closed by #55
