### ISSUE TITLE
Data assimilation resampling is hard-wired at 5-minute interval

### ISSUE THREAD

**Issue by awlostowski-noaa** [NOAA-OWP/t-route#433]
# Issue concept
The interpolation and resampling us USGS observations in `nhd_io.get_usgs_from_time_slices_folder` is hard-wired at a 5-minute interval:
```python
    usgs_df_T = (usgs_df_T.resample('min').
                 interpolate(limit = max_fill_1min, limit_direction = 'both').
                 resample('5min').  # <------ hard-wired resample interval here!
                 asfreq().
                 loc[date_time_center_start:,:])
```
# Issue manifestation
If the dt specified in the simulation yaml is 300 secs (5 mins), then this is not a problem. However, if a user specifies a different dt, then the timing of observation substitution at gage locations is incorrect. For example, the figures below show simulation results with DA for a dt = 600 sec simulation. Above the gage (first figure), the open-loop t-route simulation (blue) is reasonable compared to WRF hydro (orange). However, at the gage location, the t-route simulation is completely incorrect next to WRF hydro and these erroneous results are then routed downstream. 

### Above gage - 10 minute timestep solution closely resembles WRF solution
![image](https://user-images.githubusercontent.com/66840445/133620708-ef3ba921-08e0-48ff-8e07-77ca19685d86.png)

### At the gage - 10 minute timestep solution is wrong
![image](https://user-images.githubusercontent.com/66840445/133620889-7aa6308f-77eb-41a2-b636-530a3b05d296.png)

# Proposed solution
use dt from yaml to control resampling interval 

@jameshalgren

**Comment by jameshalgren** [comment]
Good point, @awlostowski-noaa. This TODO logs a point in the code where such a parameter might be read for later use in a more flexible interpolation scheme: 
https://github.com/NOAA-OWP/t-route/blob/4ec74cc70d4f1ca407d20a6764b3f89facb43a96/src/python_framework_v02/troute/nhd_network_utilities_v02.py#L690

**Comment by jameshalgren** [comment]
@jhrehanoaa 
This needs to be connected to dt: 
https://github.com/NOAA-OWP/t-route/blob/4ec74cc70d4f1ca407d20a6764b3f89facb43a96/src/python_framework_v02/troute/nhd_io.py#L776

This needs to be an `interpolation_length`
https://github.com/NOAA-OWP/t-route/blob/4ec74cc70d4f1ca407d20a6764b3f89facb43a96/src/python_framework_v02/troute/nhd_io.py#L652

This needs to be a `QC_threshold`
https://github.com/NOAA-OWP/t-route/blob/4ec74cc70d4f1ca407d20a6764b3f89facb43a96/src/python_framework_v02/troute/nhd_io.py#L757

**Comment by jhrehanoaa** [comment]
PR #441 will address this
