### ISSUE TITLE
time handling of qlaterals and upstream bounds in diffusive wave model

### ISSUE THREAD

**Issue by awlostowski-noaa** [NOAA-OWP/t-route#435]
@kumdonoaa 
Here is how we are currently defining the time vector of lateral inflow data in the diffusive wave Fortran kernels:
https://github.com/NOAA-OWP/t-route/blob/17c0013339162a5b4f1925884f3c68687e7ec53e/src/fortran_routing/diffusive_v02frwk/diffusive_cnt/diffusive_cnt.f90#L231-L233
I think this is incorrect, because in this context t0 is the initial condition time of the simulation. In fact, the first lateral inflow data point is not for the initial condition time, but rather for the first WRF hydro timestep (usually 1-hour) beyond the initial simulation time. 
A more accurate representation of the qlateral time would look like this:
``` fortran
do n=1, nts_ql_g
     tarr_ql(n)= (t0_g*60.0 + dt_ql_g/60) + dt_ql_g*real(n-1,KIND(dt_ql_g))/60.0 !* [min]
end do
```
# What is the time arrangement of qlateral data?
Any simulation is initialized with some warm start (initial condition) states, often contained in `HYDRO_RST` files. The timestamp of the warm start states is the timestamp of the simulation initial condition. For example, let's say that the warm start data are at 00:00. Now, for the first timestep of the simulation (00:00+dt), we DO NOT use lateral inflow data from 00:00, but rather lateral inflow data timestamped at 00:00+dt. In this way, lateral inflow data are temporally retrospective.

**Comment by awlostowski-noaa** [comment]
# Reservoir (and Muskingum Cunge) simulation time
Reservoir and Muskingum Cunge simulations write out results for all simulation timesteps AFTER the initial condition. So, for a dt = 300 sec simulation with 12 timesteps (total duration = 300 sec * 12 = 1 hour) the time array of the model result is: 
```
time = [5min, 10min, 15min, 20, 25, 30, 35, 40, 45, 50, 55, 60]
len(time) = 12
```
## what does this mean for diffusive wave upstream boundary conditions?
Downstream of reservoirs, reservoir outflows are used as upstream boundary conditions for diffusive wave simulations. So the data in `ubcd_g[1,j]` is the NOT the upstream inflow at the initial condition, rather the inflow at the second model timestep. Because it is associated with timestep = 5min, not 0min (see above).

**Comment by kumdonoaa** [comment]
For diffusive to be aligned with the time steps of MC, wrf-hydro qlateral, and reservoir,
1. qlateral (assuming time step =60 min)
    as Adam recommended, tarr_ql = 60, 120, 180, ... 
                                             qlat      = ql(60), ql(120), ql(180), ...  are provided from the framework.
     Then, diffusive interprets as

![image](https://user-images.githubusercontent.com/54687070/133816570-9ede91b5-ad9f-4e75-8654-f30bf128dd3d.png)

2. iniq and ubcd_g (assuming time step is 5 min)
    tarr_ub = 5, 10, 15, ...    &  ubcd_g = ub(5), ub(10), ub(15) ... are provided from the framework.
 
    Then, diffusive interprets as
![image](https://user-images.githubusercontent.com/54687070/133817310-289ce2b2-df45-4f0c-aef7-6c9f019d88df.png)
