### ISSUE TITLE
Mainstem only diffusive wave simulation

### ISSUE THREAD

**Issue by awlostowski-noaa** [NOAA-OWP/t-route#490]
As a step towards the MC-diffusive hybrid solution, lets create a diffusive wave simulation for a single stretch of mainstem river that uses MC outputs as upstream boundary conditions and/or lateral inflows. Use the Florence domain.

- [ ] Select a series of contiguous mainstem segments along the Cape Fear river. e.g. `[8831780, 8831794, 8831792, 8831798, 8831808, 8831810, 8831806, 8831818, 8831820, 8831826, 8831830, 8831832, 8831840, 8831846, 8831848, 8831858]`
- [ ] Identify all upstream and tributary connections to the mainstem reach. Query MC results (either t-route or directly from WRF Hydro). 
- [ ] Understand the best way to handle tributary inflows. As upstream boundaries or lateral inflows?
- [ ] Build a Jupyter notebook that constructs model forcings and executes the diffusive wave model(s)
- [ ] Plot diffusive wave simulation along side MC simulation at downstream segment of the mainstem reach.

**Comment by jameshalgren** [comment]
If this is not what you are already doing, you may consider using the main
stem definition from the fim group. That would potentially promote later
compatibility of other tests.

-- 
James Halgren
***@***.*** (regular email)
***@***.*** (Google)
+1 720-446-9952
