### ISSUE TITLE
Parallel simulations with reservoir DA fail

### ISSUE THREAD

**Issue by awlostowski-noaa** [NOAA-OWP/t-route#497]
I set up an extended AnA simulation that uses both stream and reservoir DA. On a single CPU - no parallel - the simulation takes a while but ultimately finishes successfully. Along the way there are plenty of warning messages thrown by `module_reservoir_utilities.F`:
https://github.com/NOAA-OWP/t-route/blob/63e1578af5edf7086df7a4106314d5f31bfdbc71/src/fortran_routing/Reservoir_Binding/Reservoirs/module_reservoir_utilities.F#L140-L142
However, once I use multiple (more than one) CPUs I get the following, rather cryptic, error message and the entire simulation fails:
```
 WARNING: Modified release to prevent maximum storage exceedance for reservoir    120051950
 at         3600  seconds after model start time.
 WARNING: Modified release to prevent maximum storage exceedance for reservoir    167204871
 at         3900  seconds after model start time.
 WARNING: Modified release to prevent maximum storage exceedance for reservoir      3022162
 at         3900  seconds after model start time.
 WARNING: Modified release to prevent maximum storage exceedance for reservoir    120051950
 at         3900  seconds after model start time.
 WARNING: Modified release to prevent maximum storage exceedance for reservoir    167204871
 at         4200  seconds after model start time.
 WARNING: Modified release to prevent maximum storage exceedance for reservoir      3022162
 at         4200  seconds after model start time.
/var/spool/pbs/mom_priv/jobs/1385598.chadmin1.ib0.cheyenne.ucar.edu.SC: line 15: 20637 Segmentation fault      python -m nwm_routing -f -V3 conus_ana_test.yaml
```
pint @hellkite500

**Comment by awlostowski-noaa** [comment]
Might this have something to do with `module_reservoir_utilities` being picked up by more than one thread at the same time?

**Comment by awlostowski-noaa** [comment]
Naïve ideas: 
- turn off print statements 
- change compiler flags so that a more verbose error is thrown

**Comment by hellkite500** [comment]
@awlostowski-noaa I don't know that you will get much better error reporting from compiler flags (if you do I would be interested in how you did that).

A segmentation fault is the result of a processes reading memory outside its allocated memory pages.  Prints should have no effect on that, and may ultimately be the best way to track down the issues (you will likely have to add a bunch more so you can see exactly where the seg fault occurs).  It is interesting that it works in serial, but fails in parallel.  This does hint at the possibility of some thread clashing in the reservoir module somewhere.
