### ISSUE TITLE
Notes on MC/diffusive CNmod code

### ISSUE THREAD

**Issue by awlostowski-noaa** [NOAA-OWP/t-route#507]
A place for Inland Team to foster an understanding of how the CNmod code for mainstem channels works and suggest ways to improve

**Comment by awlostowski-noaa** [comment]
This chunk of code initializes depth in the downstream-most node of each reach with normal depth, then calls `mesh_diffusive_backward` to instantiate depth at remaining nodes. 

https://github.com/kumdonoaa/t-route/blob/dbed6dbc17f3822bd92e13dbcb5900e193cb2305/src/fortran_routing/diffusive_v02frwk/diffusive_cnmod_mainstem/diffusive_cnmod_mainstem_f2py.f90#L347-L375

There is an interesting handling of depth arrays, `oldY` and `newY`. First, we populate `oldY` for reach bottom nodes only. Elsewhere, this array is just empty memory fillers. Then, we set `newY` values for reach bottom nodes equal to the values in `oldY`. The call to `mesh_diffusive_backward` fully populates `newY` with diffusive depths at all domain nodes. Finally, `oldY` is set equal to `newY`, because the `oldY` contains our initial depth estimates and is therefore the "old"  relative to the first "new" timestep.

**Comment by awlostowski-noaa** [comment]
https://github.com/kumdonoaa/t-route/blob/dbed6dbc17f3822bd92e13dbcb5900e193cb2305/src/fortran_routing/diffusive_v02frwk/diffusive_cnmod_mainstem/diffusive_cnmod_mainstem_f2py.f90#L376-L385

What is the purpose of this?

**Comment by awlostowski-noaa** [comment]
What is the point of writing MC-results out via the `q_ev_g` array? cant we just write out results for the "mainstem" nodes only?

https://github.com/kumdonoaa/t-route/blob/dbed6dbc17f3822bd92e13dbcb5900e193cb2305/src/fortran_routing/diffusive_v02frwk/diffusive_cnmod_mainstem/diffusive_cnmod_mainstem_f2py.f90#L419-L435

**Comment by kumdonoaa** [comment]
> https://github.com/kumdonoaa/t-route/blob/dbed6dbc17f3822bd92e13dbcb5900e193cb2305/src/fortran_routing/diffusive_v02frwk/diffusive_cnmod_mainstem/diffusive_cnmod_mainstem_f2py.f90#L376-L385
> 
> What is the purpose of this?

This is the initialization of water depth for nodes except the last node (ncomp) so that water depth for the rest nodes is at least equal or higher than that of the last node.  The main purpose is to start simulation with  lots of water (so depth) for numerical stability (not reaching to zero depth in early phase)

**Comment by kumdonoaa** [comment]
> What is the point of writing MC-results out via the `q_ev_g` array? cant we just write out results for the "mainstem" nodes only?
> 
> https://github.com/kumdonoaa/t-route/blob/dbed6dbc17f3822bd92e13dbcb5900e193cb2305/src/fortran_routing/diffusive_v02frwk/diffusive_cnmod_mainstem/diffusive_cnmod_mainstem_f2py.f90#L419-L435

You can definitely do that. I just want to make sure that q_ev_g and elv_ev_g contains information for tributaries as well (actual computation won't be impacted without putting MC to them)   When handling out_q and out_elv, they contain all info both from MC and Diffusive. But if we plan to handle output seperately,  we can simply ignore it.

**Comment by kumdonoaa** [comment]
> This chunk of code initializes depth in the downstream-most node of each reach with normal depth, then calls `mesh_diffusive_backward` to instantiate depth at remaining nodes.
> 
> https://github.com/kumdonoaa/t-route/blob/dbed6dbc17f3822bd92e13dbcb5900e193cb2305/src/fortran_routing/diffusive_v02frwk/diffusive_cnmod_mainstem/diffusive_cnmod_mainstem_f2py.f90#L347-L375
> 
> There is an interesting handling of depth arrays, `oldY` and `newY`. First, we populate `oldY` for reach bottom nodes only. Elsewhere, this array is just empty memory fillers. Then, we set `newY` values for reach bottom nodes equal to the values in `oldY`. The call to `mesh_diffusive_backward` fully populates `newY` with diffusive depths at all domain nodes. Finally, `oldY` is set equal to `newY`, because the `oldY` contains our initial depth estimates and is therefore the "old" relative to the first "new" timestep.

I think I need to take a look more carefully why I designed such way.  I will circle back to it soon.
