### ISSUE TITLE
Demonstrate diffusive wave coastal coupling capability

### ISSUE THREAD

**Issue by awlostowski-noaa** [NOAA-OWP/t-route#531]
A key value proposition of the diffusive wave model is it's ability to simulate backwater impacts by coupling to a y(t) downstream boundary condition. At present, the diffusive wave model defaults directly to a normal depth downstream boundary condition. We need to build and test new capabilities that allow us to feed downstream boundary conditions to the model and evaluate their impact on routed flows and depths.

## Current behavior

- Normal depth downstream boundary. Backwater conditions are not simulated

## Expected behavior

- Ingestion of exogenous boundary condition data (depth as a function of time).
- Proper munging of boundary condition data to array structures suitable as input argument for diffusive wave Fortran kernel.
- Numerically stable diffusive wave simulations with y(t) downstream boundary. 
- Simulated backwater conditions.

**Comment by awlostowski-noaa** [comment]
@kumdonoaa I propose a hard goal for this issue - a visualization of how downstream boundary conditions affect diffusive wave simulations in the Lower Colorado domain for the next NWM Demo meeting (Wed, March 9). Either an animation of a series of plots presenting differences in longitudinal flow & depth along the mainstem of the Lower Colorado. Presentation quality, intuitive, and legible figures created with matplotlib.

**Comment by JurgenZach-NOAA** [comment]
This has been addressed, for example, in PR 573 in 2022 and, more recently, in PRs 731, 740, 763, and demonstrated in internal reports.
