### ISSUE TITLE
Incorrect indexes for dataset columns

### ISSUE THREAD

**Issue by groutr** [NOAA-OWP/t-route#54]
Looking at the columns of the Pocono1 dataset, some of the column indexes seem to be incorrect.

The MusK and MusX columns actually reference MusK and NHDWaterbody columns respectively.
The ChSlp column references the TopWdthCC column.

I think this will confound any model we use pretty thoroughly. I suggest transitioning away from indexes, which are easy to mess up and fail silently, to labels, which fail much more loudly and are more less error-prone.

@jameshalgren

**Comment by groutr** [comment]
This is addressed in #41

**Comment by jameshalgren** [comment]
Superseded by #198. 
V02 Framework uses the suggested architecture and the only task remaining is to back port that to the older version.
