### ISSUE TITLE
New test domains

### ISSUE THREAD

**Issue by shorvath-noaa** [NOAA-OWP/t-route#627]
We should create at least one new test domain for HYFeatures to be able to test t-route's various functions. Similar to LowerColorado_TX for NHDNetwork. The test domain should contain features necessary to test all of t-route's capabilities. Domain should have:
- Reservoirs + DA
    - Levelpool
    - USGS
    - USACE
    - RFC
- Streamflow nudging
- Diffusive domain 
- Headwaters
- Terminal nexus points

## Current behavior
We can run tests on geopackages provided by hydrofabric team. We should check all sub-domains to see if one already meets our needs. It should also be small enough to run a test case quickly. If one does not exist, we can create our own sub-domain from the conus.gpkg.

## Steps to replicate behavior (include URLs)

1.

**Comment by shorvath-noaa** [comment]
@JurgenZach-NOAA

**Comment by JurgenZach-NOAA** [comment]
Addressed: created Lower Colorado V4 w./ all requested features: PR 653, 672, 679
