### ISSUE TITLE
R-route not running in NGIAB.

### ISSUE THREAD

**Issue by zhyccu** [NOAA-OWP/t-route#652]
I try the NGIAB(https://github.com/CIROH-UA/NGIAB-CloudInfra) which includes the r-route and Next-Gen. It seems the r-route is not working.

I tested turn-on and turn-off t-route in the realization file. I got totally same discharge (show in attached figure) at the outlet nexus.

## Screenshots

![Picture299](https://github.com/NOAA-OWP/t-route/assets/47374491/953ecaec-bccc-497f-825c-dd20950bae5a)

**Comment by zhyccu** [comment]
I used the wrong output file. the result of t-route output is like "flowveldepth_HY_Features Test.csv"

**Comment by jameshalgren** [comment]
@zhyccu 
Thanks for posting the closure. Can you post the new graph, just for reference?

**Comment by zhyccu** [comment]
Sure. Thank you for your suggestion.
Here is the result.
![Slide6](https://github.com/NOAA-OWP/t-route/assets/47374491/97dc592b-4142-4a20-adae-9ca65e623897)

**Comment by jameshalgren** [comment]
Would you be willing to post a version of your test files on Hydroshare?
