### ISSUE TITLE
Reconfigure network utilities file 

### ISSUE THREAD

**Issue by jhrehanoaa** [NOAA-OWP/t-route#73]
The reservoir code that Juzer provided regarding flow rates at timesteps works on an old version of the network utilities file. It needs to be reconfigured to work with the new version of NNU so that it can be spliced with the fortran wrapper for reservoir computation.

**Comment by jameshalgren** [comment]
@jhrehanoaa Please mark this complete with #90

**Comment by jhrehanoaa** [comment]
closed with #90
