### ISSUE TITLE
Neural network accuracy 

### ISSUE THREAD

**Issue by jhrehanoaa** [NOAA-OWP/t-route#74]
Need to find a way to improve the NN accuracy by about 1 significant figure. Reached out to Trey already and will be continuing to research possible solutions.

**Comment by jameshalgren** [comment]
@jhrehanoaa 
I tagged this as part of v01 technical debt -- really, what this needs to become is a research topic. We'll have to see if we can bring this back when we get to exploring options for nextgen and taking things to the next level of performance.
