### ISSUE TITLE
Auto compile cython and appurtenant code for v02 simulations

### ISSUE THREAD

**Issue by jameshalgren** [NOAA-OWP/t-route#80]
the v01 scripts all force compile (via f2py) the appurtenant fortran code. 

A similar capability for the cython might be useful.

**Comment by jameshalgren** [comment]
tag @groutr

**Comment by jameshalgren** [comment]
@awlostowski-noaa 
We could take a moment to write a compile function based on code in your notebooks. Let's discuss. Could hand off to @jhrehanoaa or @jdhondia-noaa

**Comment by groutr** [comment]
I think this would be better solved via a makefile for shell script. The python scripts should make the assumption that its dependencies are already resolved.

**Comment by jameshalgren** [comment]
Closed with #171
