### ISSUE TITLE
Large git objects slow down clones/pulls

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/t-route#9]
Cloning this repository is HEAVY.  It pulls a lot of text data and is quite slow.  This testing/data might need to be refactored in a way the test data can stored outside the code repository, perhaps in a t-route-testing repo, and think linked via a sub-module or some other mechanism so that code can be pulled quickly and efficiently.

**Comment by jameshalgren** [comment]
**Short story:** 
The largest file is already on the internet. That wasn't something I was fully aware of at the beginning of this process. At this point, it makes a lot of sense to add a script to download it to the appropriate location in the file structure and then call that script if the file is missing when a test is performed.

**More detail**
The heavyweight (~80Mb of the total ) is the NWM route-link file which is the basis for all of the tests (the mask files allow for sub-sets from within the larger domain). That file is here in the repo: 
./test/input/geo/Channels/RouteLink_NWMv2.0_20190517_cheyenne_pull.nc

The file in the we have in the repository contains exactly the same information as this file on the NCO site: 
https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/nwm.v2.0.2/parm/domain/RouteLink_NHDPLUS.nc

The NCO file is completely uncompressed (~270Mb), so it occupies about 3 times the bandwidth to download (though I suppose the NOAA connection is less throttled for large objects...)

The following command sequence produces a binary identical version of the file in the repo from the file on the NCO site. 
```
export ROUTELINK="RouteLink_NHDPLUS.nc"
wget -c https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/nwm.v2.0.2/parm/domain/$ROUTELINK nccopy -d1 -s $ROUTELINK ${ROUTELINK/\.nc/_compressed.nc}
```

**Comment by jameshalgren** [comment]
Who wants to add something to `./src/python_framework/nhd_network_utilities.py` to replace the reference to the in-repo file to the www version?

**Comment by jameshalgren** [comment]
PR #25 Should remedy this issue.
