### ISSUE TITLE
README usage instructions out of date

### ISSUE THREAD

**Issue by jdmattern-noaa** [NOAA-OWP/t-route#92]
Some paths and files don't exist:

cd src/fortran_routing/mc_pylink_v00/MC_singleCH_singleTS/
f2py3 -c varSingleChStime_f2py.f90  MCsingleChStime_f2py_clean.f90  -m mc_sc_stime
cd -
cd src/python_routing_v02/
Execute a serial (~2.5 minutes) and a parallel test (~0.5 minutes)
times from 6 cores (x2 threads per core), 3.7GHz
python3 compute_nhd_routing.py; python3 parallel_compute_nhd_routing.py

**Comment by jameshalgren** [comment]
@jhrehanoaa 
Let's discuss.

**Comment by jameshalgren** [comment]
Fixed with #171
